repos:
  - repo: https://github.com/psf/black
    #this version is synced with the black mentioned in .github/workflows/ci.yml
    rev: 24.4.2
    hooks:
      - id: black
        entry: bash -c 'black "$@"; git add -u' --
